# add user
POST http://localhost:9000/api/v1/user
Content-Type: application/json

{
"name":"Test Test",
"email":"email@com",
"password":"1234"
}

###get transaction
GET http://localhost:9000/api/v1/user


# transaction
###get transaction
POST http://localhost:9000/api/v1/transaction
Content-Type: application/json
Authorization: 64b3c09f2ba47c9800061c92

{
    "type":"income",
    "name":"Work",
    "amount":5000
}


###get transaction
GET http://localhost:9000/api/v1/transaction
Authorization: 64b7aea8eddb02efe2a3fac5


###delete transaction
DELETE  http://localhost:9000/api/v1/transaction
Content-Type: application/json
Authorization: 64b7aea8eddb02efe2a3fac5

[
    "64b7aeededdb02efe2a3fadc", "64b7aee3eddb02efe2a3fad7"
]